# This file was *autogenerated* from the file coloravoid.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1)
k = _sage_const_3 
n = k*k
L= []
for nu in xrange(_sage_const_1 ,k+_sage_const_1 ):
    for i in xrange(_sage_const_1 ,k+_sage_const_1 ):
        for j in xrange(_sage_const_1 ,k+_sage_const_1 ):
            L.append( ( (nu-_sage_const_1 )*k+i, (i-_sage_const_1 )*k + j, (nu-_sage_const_1 )*k + j))

for i in xrange(len(L)):
    for j in xrange(i):
        k = sum( ( L[i][t] <=L[j][t] for t in xrange(_sage_const_3 )))
        if (k>_sage_const_1 ):
            print("SHIT")
            print(i,j,L[i],L[j])

L2 = [( y,z+n,x) for (x,y,z) in L]


print(L2)
G = BipartiteGraph(None)
G.add_vertices(range(_sage_const_1 ,n+_sage_const_1 ),left=True)
G.add_vertices(range(n+_sage_const_1 ,_sage_const_2 *n+_sage_const_1 ),right=True)

G.add_edges(L2)

col = {}
for i in xrange(_sage_const_1 ,n+_sage_const_1 ):
    col[i] = (i/n,_sage_const_1 -i/n,_sage_const_1 )
G.plot(color_by_label=True).show()
raw_input("{RESS ENTER")
