# This file was *autogenerated* from the file gen.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_10 = Integer(10)
from subprocess import call
import os

def generate_ineq(G):
    f = open("current.ieq","w")
    n = len(G.vertices())
    f.write("DIM = %d\n"%n)
    f.write("\nVALID\n")
    f.write(" ".join(["0" for x in xrange(n)]) + "\n")
    f.write("\nLOWER_BOUNDS\n")
    f.write(" ".join(["0" for x in xrange(n)])+ "\n")
    f.write("\nUPPER_BOUNDS\n")
    f.write(" ".join(["1" for x in xrange(n)])+ "\n")
    f.write("\nINEQUALITIES_SECTION\n\n")
    for cliq in G.cliques_maximal():
        cur = "+".join([" x%d "%(v+_sage_const_1 ) for v in cliq]) + " <= 1"
        f.write(cur+"\n")
    f.write("\nEND\n")
    f.close()


def check(filename):
    f= open(filename,"r")
    for line in f:
        if line.find("CONV_SECTION") != -_sage_const_1 :
            break

    for line in f:
        if line.find("END")!=-_sage_const_1 :
            break
        k = line.find(")")
        line = line[k+_sage_const_1 :]

        for num in line.split():
            if num.find("/") != -_sage_const_1 :
                if (int(num.split("/")[_sage_const_1 ])>_sage_const_2 ):
                    return False
            
    return True


def generate_all( n, output_filename):
    C7 = graphs.CycleGraph(_sage_const_7 ).complement()
    output = open(output_filename,"w")
    count=_sage_const_0 
    for K in graphs.nauty_geng(str(n)+" -c "):
        if (K.subgraph_search(C7) is not None):
            continue
        count+=_sage_const_1 
        generate_ineq(K)
        if os.path.isfile("current.ieq.poi"):
            os.remove("current.ieq.poi")
        call(["traf current.ieq"],shell=True)
        if not check("current.ieq.poi"):
            print(K.vertices())
            print(K.edges(labels=None))
            K.show()
            raw_input("PAUSE")

    print("--------Looks like there are no counter examples after trying %d"%count)


if __name__=="__main__":
    #    C = graphs.CycleGraph(9)
    #generate_all(7)
    #print(check("current.ieq.poi"))
    n =_sage_const_10  
    G = graphs.CompleteGraph(n)
    for i in xrange(n):
        G.add_edge(i,i+n)
        G.add_edge(i+n,_sage_const_2 *n)
    G.show()
    raw_input("PRESS ENTER")
    generate_ineq(G)


