# This file was *autogenerated* from the file points.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5)
from sage.plot.plot3d.shapes2 import Line
n = _sage_const_5 
L = []
for k in xrange(n):
    for i in xrange(_sage_const_1 ,n+_sage_const_1 ):
        for j in xrange(_sage_const_1 ,n+_sage_const_1 ):
            L.append((i+k*n,j+k*n,(i-_sage_const_1 )*n+j))

L2 = Line(L,corner_cutoff=_sage_const_0 )
show(L2)
raw_input("ENTER")
for i in L:
    print(i)

print("DONE LIST L")
        
M= {}
for i  in xrange(len(L)):
    for j in xrange(len(L)):
        vec = (L[i][_sage_const_0 ]-L[j][_sage_const_0 ],L[i][_sage_const_1 ]-L[j][_sage_const_1 ],L[i][_sage_const_2 ]-L[j][_sage_const_2 ])
        M[vec] = M.get(vec,_sage_const_0 ) + _sage_const_1 

for i in xrange(_sage_const_1 ,len(L)):
    j = i-_sage_const_1 
    vec = (L[i][_sage_const_0 ]-L[j][_sage_const_0 ],L[i][_sage_const_1 ]-L[j][_sage_const_1 ],L[i][_sage_const_2 ]-L[j][_sage_const_2 ])
    print(vec)
#
#a = M.items()
#a.sort(key=(lambda x: x[1]))
#for x in a:
#    print(x)

